### ISSUE TITLE
update ecstatic version due to known security vulnerability

### ISSUE THREAD

**Issue by billmaimone** [mapd/mapd-charting#143]
I notice in this repo a security alert pointing at security vulnerability in pre-2.0 version of ecstatic.  This should be upgraded.

**Comment by clhenrick** [comment]
@billmaimone I believe this is only used by the `http-server` module which is used to run the demos locally, it's not present in the source code as far as I can tell.

**Comment by micahstubbs** [comment]
![screen shot 2018-01-19 at 4 46 34 pm](https://user-images.githubusercontent.com/2119400/35177858-52f69b1a-fd38-11e7-9721-3c1b9ae696e6.png)

![screen shot 2018-01-19 at 4 46 34 pm](https://user-images.githubusercontent.com/2119400/35177861-5ba964ea-fd38-11e7-9ed0-fb4c42b55425.png)
