### ISSUE TITLE
Simplify How To Use Library

### ISSUE THREAD

**Issue by mrblueblue** [mapd/mapd-charting#36]
Using this library should be a simple matter of installing the package and importing it (or using a bundle)

Currently, its very cumbersome to use this library. One has to import it like so:

```js
require("script-loader!mapbox-gl/dist/mapbox-gl.js");
require("script-loader!mapbox-gl/dist/mapboxgl-overrides.js");
require("mapbox-gl/dist/mapbox-gl.css");
require("@mapd/mapdc/mapdc.css");
require("@mapd/mapdc/scss/chart.scss");

import * as dc from "@mapd/mapdc";
const d3 = dc.d3;
```

One must also create a webpack config file like this:

```js
var webpack = require("webpack");
var path = require("path");

module.exports = {
  entry: {
    app: [
      "script-loader!@mapd/connector/dist/browser-connector.js",
      "./index.js"
    ]
  },
  devtool: "source-map",
  output: {
    path: path.resolve(__dirname, "assets"),
    publicPath: "/assets/",
    filename: "bundle.js"
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: [
          path.resolve(__dirname, "../../src"),
          path.resolve(__dirname, "../../index.js"),
          path.resolve(__dirname, "index.js"),
          path.resolve(__dirname, "node_modules/@mapd/mapdc")
        ],
        loader: "babel-loader"
      },
      {
        test: /\.css$/,
        use: [{ loader: "style-loader" }, { loader: "css-loader" }]
      },
      {
        test: /\.scss$/,
        use: [{ loader: "style-loader" }, { loader: "css-loader" }, { loader: "sass-loader" }]
      }
    ]
  }
```

**Comment by Drecula** [comment]
https://github.com/mapd/mapd-charting/issues/38

**Comment by mrblueblue** [comment]
For some inspiration, [here](https://github.com/reactjs/redux/blob/master/package.json#L23) is how `redux` packages itself.

In the end, its a node module that provides three distributions: `umd`, `es`, and `commonjs`.

```
|-- mapd-charting
    |-- dist          # for umd and css distribution
    |-- es            # es distribution
    |-- lib           # commonjs distribution
```

Here are things we need as well:
* one distributed css file in the `dist` filter. This css bundle will be a compilation of all the scss and css (including the css from the mapbox library)
* include mapbox as a dependency (rather than a peer dependency)


In the end the user should just have to import our js module/bundle and css bundle to get started.

**Comment by mLuby** [comment]
Agreed. Let's start with the use case
```sh
npm install mapd-charting
```
```js
import Charting from "mapd-charting"
```
and go from there.
