### ISSUE TITLE
enforce `cap` on rowChart as required property. 

### ISSUE THREAD

**Issue by shusson** [mapd/mapd-charting#62]
## bug :beetle: 
  - [ ] Operating System and version:
OSX 10.12.5
  - [ ] Browser and version:
Chrome 59
  - [ ] Steps to reproduce (including dashboard link):
Create a rowChart without a `cap` but with an overridden `order`
  - [ ] Description of issue:
```
dc.rowChart('#chart')
    .width(300)
    .height(300)
    .dimension(myDim)
    .cap(30) // if this is removed, the chart will no longer be ordered by 'key0'
    .group(chromGroup.order('key0'));
```

**Comment by nytai** [comment]
Hi @shusson, I'd suggest adding a high cap, say 10,000 or 100,000.
While it is true that we support a row chart without `cap`, for practical reasons, you wouldn't want a row chart with (possibly) infinite number of rows sent over the network and rendered to svg in the browser. 

We do have a ticket open for infinite scroll https://github.com/mapd/mapd-charting/issues/57 which would achieve the behavior, I suspect, you're looking for.

**Comment by shusson** [comment]
That's fine, but some documentation would be helpful. It's not clear from the API that these two behaviours are coupled and it caused a lot of head scratching.

**Comment by nytai** [comment]
Agreed, our documentation has quite a few holes at the moment. I'm going to reopen this issue and rename it to enforce `cap` until infinite scroll is implemented.
